# Generated by Django 4.2.2 on 2023-06-11 16:59

from django.db import migrations


def populate_status(apps, schemaeditor):
    raw_data = {
        "To Do": "Issues that need to be done still",
        "In Progress": "Issues that are started but not completed",
        "Done": "Issues that are completed"
    }
    Status = apps.get_model("issues", "Status")
    for key, val in raw_data.items():
        status_obj = Status(name=key, description=val)
        status_obj.save()


def populate_priority(apps, schemaeditor):
    raw_data = {
        "Low": "Low priority",
        "Medium": "Medium priority",
        "High": "High priority"
    }
    Priority = apps.get_model("issues", "Priority")
    for key, val in raw_data.items():
        priority_obj = Priority(name=key, description=val)
        priority_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [migrations.RunPython(
        populate_status), migrations.RunPython(populate_priority)]
