# Generated by Django 4.2.2 on 2023-06-11 19:40

from django.db import migrations


def add_manager_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.create(
        name='Manager', description='The manager with administrative privileges')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role_alter_customuser_team'),
    ]

    operations = [
        migrations.RunPython(add_manager_role),
    ]
